#!/bin/sh
########################################################################
# Begin ckb-next-daemon
#
# Description : Start ckb-next daemon
#
# Author      : Llamatron
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            ckb-next
# Required-Start:      $local_fs $remote_fs
# Required-Stop:       $local_fs $remote_fs
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Corsair keyboards and mice driver
# Description:         Control settings of some Corsair keyboards and mice
# X-LFS-Provided-By:   BLFS / LFS 7.0
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
   start)
      log_info_msg "Starting ckb-next-daemon..."
      start-stop-daemon --start --quiet --exec /usr/bin/ckb-next-daemon --background
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping ckb-next-daemon..."
      killproc /usr/bin/ckb-next-daemon
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc /usr/bin/ckb-next-daemon
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End ckb-next-daemon

